### ISSUE TITLE
Tutorial Issue: Missing Function "generate_blocks_2party"

### ISSUE THREAD

**Issue by thatsheepishcoder** [data61/blocklib#30]
It appears there is a missing function within the blocklib library that is trying to be used in the tutorial notebook found in the _/docs/tutorial_ folder.

When running the notebook, the program will stall on the `from blocklib import generate_blocks_2party` line. `generate_blocks_2party` is not present in the "_init_.py" file of blocklib. 

Issue replicated when building the package from it's git repo and installing through pip.

An example of the error is shown in the image attached.

![screenshot_blocklib_error](https://user-images.githubusercontent.com/54159896/71789627-40d6fd80-3080-11ea-9d3b-501e7643a9ce.png)

**Comment by JoyceXinyueWang** [comment]
Hi thatsheepishcoder, thanks for raising the issue. A PR is created to fix this and @hardbyte will review it. Feel free to have a look at the PR and leave some comments!

**Comment by thatsheepishcoder** [comment]
Thanks JoyceXinyueWang, looks great! Thanks for the fix.
